[package]
name = "caja-fantasma-once-human"
version = "1.8.0"
description = "Seguimiento de Caja Fantasma y Rueda Visional para Once Human"
authors = ["OscarD0823"]
edition = "2021"

[lib]
name = "caja_fantasma_once_human_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-autostart = "2"
tauri-plugin-opener = "2"
tauri-plugin-process = "2"
tauri-plugin-updater = "2"

[dev-dependencies]
minisign-verify = "0.2.5"
